### ISSUE TITLE
Sausage Roll TODO

### ISSUE THREAD

**Issue by zoetrope69** [zaccolley/greggs-sims-4-stuff-pack#1]
+ [x] Make it have meat in metadata
+ [x] Remove 'baked at Greggs HQ' description. Can keep it simple and generic incase you want to use it outside of a Greggs
+ [x] Remove blank description in Bake menu
+ [x] Lower freshness time
+ [x] Lower price
+ [ ] Need to fix texture/model
+ [ ] LOD 1 versions of all models...
+ [ ] Make vegan alternatives
+ [ ] Copy over text to other languages
+ [ ] Test in restaurant context
